### ISSUE TITLE
board-add-task is broken

### ISSUE THREAD

**Issue by xian-lee** [haith2m/taskbot#1]
![image](https://github.com/haith2m/taskbot/assets/138685840/39b5baaa-8952-446d-9c07-2231260e78fe)

**Comment by haith2m** [comment]
Bug fixed in commit [a3bcec5](https://github.com/haith2m/taskbot/commit/a3bcec5cd12fd34bb86aee38863e4adb28b3ebc8). Sorry for the long delay.
